### ISSUE TITLE
'Manual' overrides by administrator

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#2]
Would it be possible for the administrator to make a booking on behalf of a client (eg someone not a BMC member but with a legitimate reason for using the hut) and effectively override the validation process? Also under the present system it is not possible to alter a booking (dates/number of beds) on behalf of a client.

**Comment by asimshah** [comment]
Please try and avoid raising multiple distinct matters as a single issue. In this case, for example, altering a booking has nothing to do with making a booking on behalf of a client. The giveaway is that the sentence begins with 'also' ...

We need to be able to discuss on behalf bookings by adding comments like this and in the process the altering of a booking will inevitably get lost (or the other way round).

Avoid writing an essay and try and raise a single topic as an issue. Sometimes it will happen that a topic turns out to be more complex but let me worry about what to do when that happens.

Note also that it is not at all the case that the title "manual overrides ....' suggests 'on behalf bookings' in a clear way. Consequently as the number of issues recorded increases it will become difficult to find an issue easily.

**Comment by mikebattye** [comment]
I see what you mean.

Regards,

Mike
From Samsung tablet.

--- Original Message ---
