### ISSUE TITLE
Dual calendars

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#22]
Having played with the booking app I wonder if displaying the top availability calendar is necessary (especially on a mobile device). You can find what is available by selecting the appropriate month in the select date calendar.

**Comment by mikebattye** [comment]
Either way they will need some sort of legend.

**Comment by asimshah** [comment]
It is good question. The multiple months on a wide screen does allow for a better oversight of availability. Plus there is the real question of whether it is possible to select a day on a touch device - have you tried on a phone as I haven't as yet.
As far as the legend is concerned, I plan to have one when on a wide screen but I am trying to devise a solution for phones which works within the limited screen space (and, of course, you cant hover on a phone and see the tooltip!) Ideas welcome...

**Comment by mikebattye** [comment]
Works fine on my S5 (5" screen) including selecting days.
The availability calendar should display when you are not logged in but is redundant when booking IMO.
There are only 4 states to display (free, partial, full, blocked) correct? On my phone a legend would fit comfortably alongside a single month calendar.
Does anyone use a phone less than 4" nowadays? Or if they do would they use apps at all?

Sent from my Samsung device

-------- Original message --------

**Comment by asimshah** [comment]
If you mean by "alongside a single month calendar" adjacent to the month calendar that pops up (meaning the legend should pop up with the calendar pop up) then that is probably impossible - the calendar is not my code and I doubt if I could modify it as it is quite complex.
The legend needs to shown in some other place/some other way. There are 5 states as Saturdays are shown are "not separately bookable".

**Comment by mikebattye** [comment]
Not sure what you mean by pop-up. I'm talking about the calendar that displays availability for each month that appears above 'Select Dates',

**Comment by asimshah** [comment]
by pop-up I mean that the calendar month "pops-up" when you click on the relevant input box (there are two such boxes: for Arrival and for Departure. "Pop-up" means this month box is not shown until and unless the user clicks, or in any other way focus changes to, the associated input box.
These "pop-ups" are different from the "permanent" display of calendar months - these vary in number from 1 to 4 months depending upon the current window width. It is my impression that you wanted these "permanent" calendar months to be removed (as the same information is available in the months that "pop-up" except that it is only for the current month).
if you re-read your original comment, I think that you were actually talking about the legend appearing beside ("alongside") a month calendar as the "availability" calendar is redundant - so it is NOT that case that you are talking about " ... the calendar that displays availability for each month that appears above 'Select Dates',". 
It may be better to take a screen shot of the case you mean (on a desktop by narrowing the window to the height and width of your phone) and that indicating on that where you think the legend might appear instead of all these words that serve only to confuse and delay .....

**Comment by asimshah** [comment]
can I consider this matter closed?
