### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#27]
Nothing happens when I try to register a new member.

![capture1](https://cloud.githubusercontent.com/assets/11847651/11332980/3d3cba68-91c2-11e5-933d-9d7e93a8fe74.JPG)

**Comment by mikebattye** [comment]
I'm still not able to register on the site as a new member. Am I missing something?

**Comment by asimshah** [comment]
When I tried this after the fix referred to above, I got a message back on hitting the registration button that read something like "No BMC record found".
I have tried again this morning an I am getting a 403 Forbidden response from the bmc test server when I do it with my system here but nothing when I do it with the dwh test system.
There are multiple layers in operation here and there may be issues with more than one of them. 

1.Remember that no one can self-register if they are not a BMC member and this is checked at registration time. This morning I am unable to get part this stage because something has gone wrong with communication with the BMC test server - it could be anything but in effect 403, Forbidden means I am not allowed (at the moment at least) to make any request. (This was the gist of my previous emails about this. Regardless of any assurances from any body about this membership check api, it can fail from time to time - we have no definition of what we are supposed to about it and I have programmed it accordingly: the code expects to always be able to successfully communicate with the BMC server and get an answer. This morning it is failing and the no one can register).

2. You should always get some sort of message back after you hit Register. There should be a waiting icon, flowed by a message or, if successful, you should go to the next step. This works on my system but for some not on the dwh test system. I need to figure out why this is but I am hampered by the fact that this morning the call to the BMC server is itself failing ...

I will try again later today or tomorrow and if the problem persists then we may need to discuss what is the best strategy.

**Comment by mikebattye** [comment]
OK.

Speak to you on Monday - have time now we are back from Istanbul.

M

**Comment by asimshah** [comment]
I have upgraded dwh.test.webframe.co.uk a few minutes and this version should handle registration better.
It is still the case that the BMC api is failing. You should see the result when you try and register a new member using self-registration. Given that BMC membership is a requirement, it follows that you will not be able to create new members using self-registration.
I suggest you try it and confirm that you are getting a message, albeit a non user friendly one. You could then contact Alvin and ask him if he can resolve whatever the issue is and then try again.
Remember that you should be able to create members without BMC numbers using the membership app.

**Comment by mikebattye** [comment]
This now works.
