### ISSUE TITLE
Listing by Booking Ref order

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#39]
In View Bookings listing is alphabetical not date order in Booking Ref field. Thus Mar16xxx comes after Aug16xxx. You can adapt to this but it could be confusing.

**Comment by asimshah** [comment]
This is because the booking ref is not a date but a string! It is originally built using the date in order that we get a simple reference which is guaranteed to be unique. It could alternatively be some geeky construction that would be harder to use. I discussed this with you at the very beginning ...
