### ISSUE TITLE
Save changes

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#40]
Did you consider a pop up if changes are made but not saved? Eg if a booking is cancelled and then box is closed it could prompt you with something like 'Do you wish to save changes?'.

**Comment by asimshah** [comment]
I agree that this dialog is not ideal. In fact, when you press cancel, the booking is cancelled immediately you do not need to use Save Changes. It is like this because you can edit the mobile number and that requires a "Save Changes". ("Cancel" is not a "change" of the booking data ...). An alternative might be to simply close the dialog after Cancel. Adding a further prompt is not so straight forward.

**Comment by mikebattye** [comment]
Closing the dialog on cancel could help.

**Comment by asimshah** [comment]
I have had another look at this and closing the dialog on cancel will make matters worse - the user is left uncertain what exactly has happened because there is no opportunity to read the message that states that the booking has been cancelled (the dialog having closed).

I propose to leave this as it is (though I agree it is not an ideal dialog). The only editable item is the  mobile number and perhaps we should rethink the way the mobile number retention works - recall that mark did not immediately realise what was happening when he so the mobile number reappear!

If you agree, please close.
