### ISSUE TITLE
Missing bookings

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#44]
Mark has just phoned me with this issue. If you look you look in the CMS email history there is reference to some bookings that do not appear in either the booking list or in cancelled. Thus for Aug16 there should be bookings from 003 to 009 but only 006 & 007 are listed in cancelled and there are none in bookings list. He is checking to see if he can find some from other months.

**Comment by asimshah** [comment]
The actual problem was the error that caused the Archived Bookings" not to work. I have now fixed that and upgraded the site.
Archived Bookings are all bookings that are in the past that were not cancelled (those remain in the Cancelled Bookings report). The idea is that the normal bookings report is not full of old bookings.
If you now look in that report you will see the "missing" bookings.

**Comment by mikebattye** [comment]
I thought that might be the case as Mark had looked in archived bookings and found that it wasn't functioning.



Regards, Mike

Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by asimshah** [comment]
Can this be closed?
